-- DECLARO VARIABLES DE TRABAJO
DECLARE @Y INT, @Y1 INT, @PEDIDO INT, @MONTO DECIMAL, @TOTAL
DECIMAL
SET @TOTAL=0
-- DECLARO EL CURSOR
DECLARE MI_CURSOR CURSOR FOR
SELECT YEAR(FECHAPEDIDO),
C.IDPEDIDO,
SUM(PRECIOUNIDAD*CANTIDAD)
FROM VENTAS.PEDIDOSCABE C
JOIN VENTAS.PEDIDOSDETA D ON C.IDPEDIDO=D.IDPEDIDO
GROUP BY YEAR(FECHAPEDIDO), C.IDPEDIDO
ORDER BY 1
-- ABRIR EL CURSOR
OPEN MI_CURSOR
-- LEER EL PRIMER REGISTRO
FETCH MI_CURSOR INTO @Y, @PEDIDO, @MONTO
-- ASIGNAR A LA VARIABLE @Y1 EL VALOR INICIAL DE @Y
SET @Y1 = @Y
-- IMPRIMIR EL PRIMER AÑO
PRINT 'AÑO:' + CAST(@Y1 AS VARCHAR)
-- MIENTRAS PUEDA LEER EL REGISTRO
WHILE @@FETCH_STATUS=0
BEGIN
-- SI COINCIDEN LOS VALORES ACUMULAR EL TOTAL
IF(@Y = @Y1)
SET @TOTAL += @MONTO
ELSE
-- SI NO COINCIDEN IMPRIMIR EL TOTAL, INICIALIZAR VARIABLES
BEGIN
PRINT 'IMPORTE EN:' +CAST(@Y1 AS VARCHAR) +
SPACE(2)+ 'ES ' +CAST(@TOTAL AS VARCHAR)
PRINT 'AÑO:' + CAST(@Y AS VARCHAR)
SET @Y1=@Y
SET @TOTAL=@MONTO
END
-- IMPRIMIR EL REGISTRO
PRINT CAST(@PEDIDO AS VARCHAR) + SPACE(5)+STR(@MONTO)
-- LEER EL REGISTRO SIGUIENTE
FETCH MI_CURSOR INTO @Y, @PEDIDO, @MONTO
END
-- CERRAR
CLOSE MI_CURSOR
-- LIBERAR
DEALLOCATE MI_CURSOR;
-- IMPRIMIR LOS TOTALES FINALES
PRINT 'IMPORTE EN:'+CAST(@Y1 AS VARCHAR)+SPACE(2)+'ES'+STR(@TOTAL)