-- DECLARO VARIABLES DE TRABAJO
DECLARE @NOMBRE VARCHAR(50), @Q INT, @TOTAL INT
SET @TOTAL=0
-- DECLARO EL CURSOR
DECLARE MI_CURSOR CURSOR FOR
SELECT C.NOMBRECIA,
COUNT(*)
FROM VENTAS.CLIENTES C
JOIN VENTAS.PEDIDOSCABE PC ON C.IDCLIENTE=PC.IDCLIENTE
GROUP BY C.NOMBRECia
-- ABRIR
OPEN MI_CURSOR
-- LEER EL PRIMER REGISTRO
FETCH MI_CURSOR INTO @NOMBRE, @Q
-- MIENTRAS PUEDA LEER EL REGISTRO
WHILE @@FETCH_STATUS=0
BEGIN
-- IMPRIMIR EL REGISTRO
PRINT @NOMBRE+','+CAST(@Q AS VARCHAR)
-- ACUMULAR
SET @TOTAL += @Q
-- LEER EL REGISTRO SIGUIENTE
FETCH MI_CURSOR INTO @NOMBRE, @Q
END
-- CERRAR
CLOSE MI_CURSOR
-- LIBERAR
DEALLOCATE MI_CURSOR;
-- IMPRIMIR
PRINT 'TOTAL DE PEDIDOS:' + CAST(@TOTAL AS VARCHAR)
GO

select * from ventas.clientes
select * from ventas.pedidoscabe