USE [negocios2011]
GO
ALTER FUNCTION [dbo].TOTALVENTASCLIENTE(@CLI CHAR(5)) RETURNS DECIMAL(10,2)
AS
BEGIN
DECLARE  @TOTAL AS DECIMAL(10,2)

SELECT @TOTAL = SUM(PRECIOUNIDAD*CANTIDAD*(1-descuento/100)
FROM VENTAS.PEDIDOSDETA PD JOIN ventas.PEDIDOSCABE PC
ON PD.IDPEDIDO = PC.IDPEDIDO
WHERE PC.idcliente  = @CLI
RETURN @TOTAL
END

GO
SELECT DBO.TOTALVENTASCLIENTE('NCBCK')