SELECT  C.IDPAIS , SUM(PRECIOUNIDAD*CANTIDAD)  
FROM VENTAS.PEDIDOSDETA PD JOIN ventas.PEDIDOSCABE PC
ON PD.IDPEDIDO = PC.IDPEDIDO
JOIN ventas.clientes C ON C.IDCLIENTE = PC.IDCLIENTE
WHERE YEAR(FECHAPEDIDO)=2013
GROUP BY C.IDPAIS
ORDER BY 2 DESC