use negocios2011
go
alter FUNCTION DBO.PEDIDOMAXVENTA() RETURNS INT
BEGIN
DECLARE @PEDIDO INT
DECLARE @TOTAL DECIMAL(10,2)
select @TOTAL = MAX( 
SELECT  sum(PD.PRECIOUNIDAD*PD.CANTIDAD) 
FROM VENTAS.PEDIDOSDETA PD
GROUP BY pd.IDPEDIDO)


SELECT  @PEDIDO = PD.IDPEDIDO
FROM VENTAS.PEDIDOSDETA PD
GROUP BY pd.IDPEDIDO
having  SUM(PD.PRECIOUNIDAD*PD.CANTIDAD) =@TOTAL

RETURN @PEDIDO
END
GO

SELECT DBO.PEDIDOMAXVENTA()

